project:
  type: website
  output-dir: docs
  # pre-render: # prepare.py
  # post-render: 
    # - compress.ts
    # - fix-links.py

website:
  title: "Linghao Wang"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      #- href: portfolio.qmd
      #  text: Portfolio
      #- href: kaggle.qmd
      #  text: Kaggle
      #- href: research.qmd
      #  text: Research
      - href: talks.qmd
        text: Talks
  page-footer: 
    left: "Copyright 2022 &copy; Linghao Wang"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/linghao-wang/
      - icon: github
        href: https://github.com/Waterkin
      #- icon: kaggle
      #- href: https://www.kaggle.com/waterking886"
  #google-analytics: "G-K5TXS64QLN"
  site-url: https://waterking.cc
  repo-url: https://github.com/Waterkin/my-blog
format:
  html:
    theme: 
      dark: [cosmo, theme-dark.scss]
      #dark: cosmo
    css: styles.css
    toc: true
    toc-title: Contents
    toc-depth: 3
    mainfont: Segoe UI
    #fontcolor: #515151
    # code-line-numbers: true
    code-copy: true
    code-fold: true
    code-summary: "Show the code"
    code-block-bg: "#212121" #black #true
    code-block-border-left: "#3772ff" #"#31BAE9"
    highlight-style:  ayu-dark #gruvbox  #ayu-dark
    number-sections: true
    number-depth: 3
    fig-cap-location: bottom
    tbl-cap-location: bottom
    link-external-icon: true
    link-external-newwindow: true
    shift-heading-level-by: 1
    #title-block-banner: true



execute:
  freeze: auto