---
title: "Machine Learning Engineer (Ads) Interview Questions"
subtitle: "A Guide to Pass the MLE interview."
date: "2023-01-27"
categories: [tutorial]
css: ../../../styles.css
draft: true
---

# 你之前的项目是做股票的，为什么想来做广告？

# CTR预估为什么是个分类而不是回归问题/为什么分类要用softmax而不是sigmoid

# embedding层是选择end2end模式还是预训练模式

# 推荐广告场景下，模型中采用双向循环网络，效果比单向循环网络效果好，分析好的原因在那

# 如何验证引入DIN,DIEN等序列化模型后，序列化建模是有效的

# 现有纸质资料:训练册，每本训练册前面是题目，后面是答案。在线时如何快速根据题目找到相对应的答案，意思是想训练一个模型/提出某种架构，输入一个题目就能快速匹配他对应的答案，避免前期在数据库中人工手动输入每个问题对应的答案

# 类似YoutubeDNN，双塔等向量化召回与协同过滤的区别

# 使用传统的dropout在RNN中效果不是很好，因为RNN会有放大噪音的功能，所以该如何在LSTM中使用dropout

# 如何使用一个通用的pattern，将某一个分布转换为另一个分布，参数和非参数方法均可

# DIN、LSTM的时间复杂度

# FM中隐向量的作用

# NDCG的计算公式

# 训练和推理有什么区别

# 推荐中数据不平衡，采样后，需要对点击率进行校准，如何校准？

# 对推荐算法的了解、对推荐模型的了解、推荐算法由哪几部分组成

# 如何对item的id做embedding

# 模型上线后严重下滑怎么办？有哪些原因？

# 解释业务指标，以及如何业务指标的提升是怎么量化到变现上面的

# 为什么在做CTR预估的时候需要加入一些固定的用户特征

# 如何解决推荐系统的冷启动问题

# 怎么给用户推荐内容（可以利用浏览历史等等）

# 场景题：如何在用户检索时补全 比如（j->jd, c++,j -> c++,java）

# 抖音业务相关的问题，follow行为的预测

# 你了解元学习吗？说一下你的理解。

# 千万的用户量和万级的广告，设计一个推荐系统，会对每个细节问的很详细，loss设计，embedding，模型优化等等

# 推荐算法基础，以及怎样优化排序和召回，怎样推荐给用户更合适的广告。