---
title: "English Reading"
date: "2022-10-31"
categories: [reading]
---

This is a post recording my English reading on Scientific American and the Economist.

<hr style="height:1px; visibility:hidden;" />
<hr style="height:1px;border-width:0;color:rgb(50,50,50);background-color:rgb(50,50,50)">

### 2022.10.26

She had suffered a ruptured blood vessel in her brain(脑血管破裂), and the bleeding area was putting tremendous pressure on(造成巨大压力) critical brain regions.

Uma Thurman as the Bride in Kill Bill awakens abruptly from a prolonged comatose state（从长时间昏迷状态中突然苏醒）, appears well nourished despite not having any feeding tubes and regains full physical strength within hours.

The reality is far more challenging, with frequent medical complications（并发症）, physical deterioration（身体机能衰退） and a long road of small steps forward with many steps backward.

The term “locked in” was coined（创造） in 1966 by neurologists.

In clinical practice, locked-in patients do not move their extremities（四肢）.

The experience of living in a locked-in state was poignantly illustrated by Jean-Dominique Bauby, who suffered a stroke that blocked signals traveling from the motor cortex in his brain（大脑里的运动皮层） to his spinal cord（脊髓） and limbs（四肢）.

Both techniques may also be confounded by sedative medications（和镇定剂混合使用）, which are required for safety or comfort in most critically ill patients（大多数病重患者）.

Neurologists are trying to develop a test that can identify which patients are likely to be in a state of covert consciousness（潜意识） and thus should undergo（=take，接受，经历） advanced EEG and functional MRI assessments.

But tremendous challenges must be overcome, particularly for acutely（严重的，=critically） brain-injured patients

There is no mystery, however, about the ethical imperative（an essential or urgent thing.） that physicians（医生） now have to search for consciousness in patients who appear unresponsive, using all available technologies and resources
<hr style="height:1px; visibility:hidden;" />
<hr style="height:1px;border-width:0;color:rgb(50,50,50);background-color:rgb(50,50,50)">

### 2022.10.22

This one was so close, cosmically speaking, that it was detected by a fleet of observatories（一系列的天文台） both on and above the Earth, and is already yielding a trove of（大量的） scientific treasure.

But even from this immense（非常大的） distance in human terms, it was the brightest such event ever seen in x-rays and gamma rays, bright enough to spot its visible-light emission in smaller amateur telescopes（业余的望远镜）, and was even able to physically affect our upper atmosphere. Despite that, this gamma-ray burst poses no danger to us（对我们没有威胁）. Either way（不管怎样）, I’m glad they keep their distance.

Gamma-ray bursts, or GRBs, are intense blasts（强烈的爆炸） of gamma rays—the highest-energy form of light—that typically last from a fraction of a second （顷刻间）to a few minutes in length.

Each GRB has idiosyncrasies（特质=characteristics）, making them complicated to understand as a group.

Still, we do have a decent grasp of（的确对...有比较好的了解） their basic nature.

Short-duration bursts—generally a few seconds long at most—come from two superdense neutron stars colliding（碰撞） and blasting out fierce energy（爆发出剧烈的能量, fierce=intense）, whereas（表示对比，然而但是） long-duration ones—lasting several minutes—come from massive stars exploding at the ends of their lives.

A swirling disk of material（一个旋转的圆盘状物质） that wasn’t immediately swallowed by the black hole rapidly forms around it, funneling twin beams of intense energy out into space（将两束强烈的能量注入太空）, one pointing up and the other down, away from the disk.

The energy in gamma-ray bursts is almost incomprehensible（令人费解的）: In a few seconds they can emit（排放，散发） as much energy as the sun will over its entire 12-billion-year lifespan.
<hr style="height:1px; visibility:hidden;" />
<hr style="height:1px;border-width:0;color:rgb(50,50,50);background-color:rgb(50,50,50)">

### 2022.10.21

We really need to revamp(修补，改进) our health care system and make it work for everyone in this country if we want to stop this backsliding（倒退） and live longer, healthier lives.

Look, I don’t want to keep tossing out problems（抛出问题）.

So there’s a chance（有可能） we’ll be seeing new and affordable therapies, able to handle the range of variants that COVID keeps tossing at us.

Counterintuitively(反直觉的是), taking testosterone（睾酮，睾丸产生精子需要高浓度睾酮） may also help suppress sperm production, because increasing circulating testosterone levels above a certain level suppresses the same two pituitary hormones（垂体荷尔蒙，控制睾丸产生精子）.

We may feel groggy(昏昏沉沉的) and grumpy（脾气暴躁的，这些都是睡眠不足导致的）

But have you found that sleep deprivation changes actual helping behaviors in a noticeable（显著的） way?

With anxiety, for instance, when something stresses you out（使你感到焦虑）, the first thing that gets impaired is your sleep. And paradoxically（矛盾的是）, more sleep is what you need to feel calmer.

On the flip side（另一方面）, does this mean we should really put better sleep alongside（把...视作等同于） diet and exercise as a crucial way to improve mental health?

Sleep is something that can help us intervene into（干预） social and emotional affective disorders

Sleep is actually the bedrock（基石）, even before diet and exercise. The way we metabolize（代谢） food and the way our muscles react also depends on good sleep.

The findings, published in the journal Nature Geoscience, shed new light on（进一步揭示了） the forces driving ice loss on the world’s second largest ice sheet.

Losses from these seaside glaciers have, until now, been mainly attributed to（归因于） warm ocean waters licking（波浪轻卷） at the edge of the ice.

Lead study author Donald Slater, a scientist at the University of Edinburgh, likened（把...比作） the process to ice cubes in a glass of water.








